- CHANGELOG.md
- spython/main/base/command.py
- spython/main/inspect.py
- spython/utils/terminal.py
- spython/version.py
This tweak will honor the client's quiet level when running "run_command" - currently we spit out the output no matter what!
> removing unecessary printing for inspect

- .travis/before_install
- spython/image/__init__.py
The strip removes the / symbol from the beginning of the location to load the image. This removal results in trimmed absolute paths not available for loading the container image
> changed strip to rstrip for image remove uri function

- CHANGELOG.md
- README.md
- spython/client/shell.py
- spython/version.py
This will fix a bug that the client is imported as "client" and not "cli" in the shell function, given that the user has bypython or standard python. It's been missed because **most** have ipython. This will fix #55 .
> fixing client bug, cli --> client

- CHANGELOG.md
- spython/main/base/command.py
- spython/main/run.py
- spython/version.py
This is the simplest fix to (not try parsing) a result that is None.
> simple fix to run - only parse result if one is returned

- CHANGELOG.md
- spython/instance/cmd/start.py
- spython/version.py
The bug was trying to capture the output, which hangs because we are starting a separate process namespace I think. The fix is to set capture to False.
> fixing bug with instances starting hanging!

- CHANGELOG.md
- docs/pages/commands-instances.md
- spython/image/cmd/__init__.py
- spython/instance/__init__.py
- spython/instance/cmd/__init__.py
- spython/instance/cmd/iutils.py
- spython/instance/cmd/start.py
- spython/instance/cmd/stop.py
- spython/main/__init__.py
- spython/main/base/command.py
- spython/main/instances.py
- spython/tests/test_utils.py
- spython/utils/__init__.py
- spython/utils/terminal.py
- spython/version.py
This will address the [change](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md#v300---20181008) for Singularity 3.0 that the instances subgroup is no longer one string, joined by period.
E.g., the old "singularity instance.list" is now "singularity instance list".
To support both versions for the user, we derive behavior of this client based on the singularity --version returned by the host. If the host wants to override this behavior, the environment variable `SPYTHON_SINGULARITY_VERSION` can be exported, e.g.,
```bash
export SPYTHON_SINGULARITY_VERSION=3.0
```
This will close #75
> updating instances to support singularity instances subgroup >= 3.0

- CHANGELOG.md
- spython/main/parse/docker.py
- spython/version.py
This will fix a bug that newlines in a Docker recipe are split excessively given that there isn't a command to parse. I'm not entirely confident in the fix (it seems like it might break other recipes) but the fix is overall to add a superficial space before the command so it isn't split as if it were an action. The issue is reported in #77 please test on other recipes (preferably with continued lined) to test. Thanks!
> fixing bug to parse newlines

- setup.py
Hi,
Saw the description of the project in PYPI, and also #79. I contribute to a project that also displays its `README.md` as long description. But in order for the formatting to be correctly rendered, we needed to set the content type [in the setup.py](https://github.com/metomi/isodatetime/blob/master/setup.py).
This pull request simply adds that to the `setup.py` here too :-)
Cheers
Bruno
> Fix long description content type for PYPI

- CHANGELOG.md
- spython/instance/cmd/start.py
- spython/version.py
This pull request will add an additional argument, args, to the instance start command (from within python) so the user can choose to provide arguments to the instance.
> quick addition to support args

- CHANGELOG.md
- spython/instance/cmd/iutils.py
- spython/instance/cmd/start.py
- spython/instance/cmd/stop.py
- spython/main/instances.py
- spython/version.py
This PR will fix the Client.instances() command so that if the user provides a name, a single instance is returned instead of a list. This will close #83
> fixing issue with instances, should return one

- .travis.yml
- .travis/before_install
- .travis/script
- CHANGELOG.md
- spython/main/instances.py
- spython/version.py
This pull request will close #86 , fixing the bug with instance stop all.
> fixing bug with instance stop all

- .circleci/config.yml
- CHANGELOG.md
- spython/main/base/command.py
- spython/main/execute.py
- spython/main/run.py
- spython/oci/__init__.py
- spython/oci/cmd/states.py
- spython/tests/test_client.py
- spython/tests/test_instances.py
- spython/tests/test_oci.py
- spython/version.py
This is a work in progress to address #95 and allow for exec/run (for containers and instances) to return the full result (a return code and output).
> [WIP] adding return code option to run and execute

- CHANGELOG.md
- spython/instance/__init__.py
- spython/instance/cmd/__init__.py
- spython/instance/cmd/start.py
- spython/version.py
This will fix a bug that an instance doesn't have a name if it isn't started. The instance is given a robot name on init, and if the user starts the instance with start() the name will be overridden. This will close #97 
Another update here is changing the instance._start() to instance.start() because it's a reasonable function for the user to want to interact with, and thus shouldn't be private.
> fixing instance name missing when not started

- CHANGELOG.md
- spython/main/parse/converters.py
- spython/main/parse/docker.py
- spython/version.py
- Fix #101 : Don't warn for destination files
- Fix #102 : warn when using `*` for file expansion in docker. Not supported in singularity till https://github.com/sylabs/singularity/pull/3447
Supersedes #105: Rework function to avoid useless dictionary (checks only make sense for source and expansion was factored out into function)
> Don't warn if dest file/folder does not exist

- CHANGELOG.md
- spython/image/__init__.py
- spython/image/cmd/export.py
- spython/main/__init__.py
- spython/main/base/sutils.py
- spython/main/build.py
- spython/main/export.py
- spython/tests/test_client.py
- spython/utils/terminal.py
- spython/version.py
> updates for image export, needs deprecation message

- CHANGELOG.md
- spython/main/parse/converters.py
- spython/main/parse/docker.py
- spython/main/parse/recipe.py
- spython/version.py
This will fix #114, a quick fix so that the last working directory is honored. For the recipe here, that means that we cd to /code first (shown below).
```
...
%environment
export PYTHONUNBUFFERED=1
%runscript
cd /code
exec /bin/bash "$@"
```
> fixing entrypoint accounting for WORKDIR

- .circleci/config.yml
- requirements.txt
- spython/image/__init__.py
- spython/instance/__init__.py
- spython/main/base/__init__.py
- spython/oci/__init__.py
- spython/tests/test_oci.py
- spython/tests/test_utils.py
- spython/utils/__init__.py
- spython/utils/terminal.py
- spython/version.py
Using pytest allows for faster writing of tests due to easier syntax as well as including e.g. coverage and other pytest plugins
> WIP: Use pytest for tests

- .circleci/config.yml
- spython/tests/test_oci.py
> testing with singularity 3.2.0

- .circleci/config.yml
- CHANGELOG.md
- spython/main/inspect.py
- spython/version.py
This will fix #127, specifically if the user asks inspect to be quiet, it doesn't honor this (and prints output to the screen).
> Quiet inspect

- CHANGELOG.md
- setup.py
- spython/tests/testdata/docker2singularity/entrypoint-cmd.def
- spython/tests/testdata/docker2singularity/entrypoint-cmd.docker
- spython/version.py
The testing requirements were not fully represented in the setup.py. I'm worried now that there are too many additional dependencies to run basic testing, and perhaps this will come back to bite me. For the meantime the damage is already done, and I'll need to update conda deps too. Right now as is, a user only thinks that pytest is required and won't understand why many of the tests fail. This will also add a test for the entrypoint+cmd conversion in a Dockerfile to Singularity recipe.
I will need to update conda too.
> adding test for entrypoint+cmd and adding proper testing requirements

- CHANGELOG.md
- spython/main/build.py
This will give the user more flexibility to specify custom build options (that are also likely to change) to the build command. It will close https://github.com/singularityhub/singularity-cli/issues/132.
> adding build options argument

- CHANGELOG.md
- spython/main/build.py
- spython/version.py
This will expose build arguments (quiet, return_result) to the user to allow for more programmatic control of the build. 
> adding quiet (and other args) to build

- CHANGELOG.md
- spython/main/base/command.py
- spython/main/build.py
- spython/utils/terminal.py
- spython/version.py
This allows me to pass '--preserve-env=SINGULARITY_CACHEDIR,SINGULARITY_TMPDIR' to sudo,
which I need to deal with my very small /root and /tmp partitions.
> spython.main.Client.build: add sudo_options option

- .circleci/config.yml
- CHANGELOG.md
- README.md
- spython/tests/test_client.py
This just updates the orb to 1.0.5, which should use caching for Singularity from here on out. I'll let it run, and likely need to push again to see if the cache works.
> testing addition of singularity cache to orb 1.0.7

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- spython/main/parse/parsers/singularity.py
- spython/tests/test_client.py
- spython/version.py
Currently, export lines are ignored, the thinking that they look like this:
```bash
VARNAME=thing
export VARNAME
```
however we wouldn't want to ignore this line:
```bash
export VARNAME=thing
```
Instead we would want to replace the export and result in:
```bash
ENV VARNAME=thing
```
> Allow for environment export lines that contain =

- CHANGELOG.md
- spython/main/instances.py
- spython/version.py
Newer versions of Singularity (3.5.2 from master) include the up address in the listing.
> adding support for instance list to include ip

- CHANGELOG.md
- spython/instance/cmd/stop.py
- spython/version.py
Added ability to specify stop timeout (default 10 - as for singularity instance stop specification)
> Timeout in instance stop

- CHANGELOG.md
- spython/main/build.py
- spython/main/pull.py
- spython/tests/test_utils.py
- spython/utils/terminal.py
- spython/version.py
This is a re-opening of #154 to trigger tests - it looks like Circle has added new security "features" that the orb will not run if it's a PR opened by a non-org member. This could be an issue in the future we will need to address, for now I'm trying opening here (including all commits from #154).
> Library url support

- CHANGELOG.md
- spython/image/cmd/create.py
- spython/instance/cmd/iutils.py
- spython/instance/cmd/start.py
- spython/instance/cmd/stop.py
- spython/main/apps.py
- spython/main/base/command.py
- spython/main/build.py
- spython/main/execute.py
- spython/main/export.py
- spython/main/inspect.py
- spython/main/instances.py
- spython/main/pull.py
- spython/main/run.py
- spython/oci/cmd/actions.py
- spython/oci/cmd/states.py
- spython/version.py
This will allow a user (using the Client) to add a list of any singularity options that are needed. E.g.,:
```
singularity --silent build ...
```
Could be passed to build like:
```python
Client.build(..., singularity_options=["--silent"])
```
This will close #153 
Signed-off-by: vsoch <vsochat@stanford.edu>
> adding flags (singularity_options) to init command

- CHANGELOG.md
- spython/main/parse/writers/singularity.py
- spython/version.py
We need to only replace a USER directive from a Dockerfile with a Singularity "equivalent" given that it's found at the beginning of the line, and not somewhere later (used as a different variable!) This will fix #158. 
Signed-off-by: vsoch <vsochat@stanford.edu>
> Fixing bug that user is replaced anywhere in the line

- CHANGELOG.md
- spython/main/parse/writers/singularity.py
- spython/tests/test_client.py
- spython/utils/terminal.py
- spython/version.py
**Is your feature request related to a problem? Please describe.**
When streaming with spython, `stdout` is yielded to a generator, and if the subprocess's `return_code` is not `0`, a `CalledProcessError` is raised. The contents of `stderr` is not passed in either case.
**Describe the solution you'd like**
This pull request adds the contents of `stderr` to `stdout` so the generator contains both in the same sequence as they would be presented if run outside of spython.
**Describe alternatives you've considered**
Alternatively, the contents of stderr could be included in the `CalledProcessError` to give the user details of the exception separate from `stdout`.
**Test your PR locally, and provide the steps necessary to test for the reviewers.**
I'm using this branch in the [develop branch …
> 🚸 Add `stderr` to generator when streaming

- CHANGELOG.md
- docs/pages/recipes.md
- spython/main/parse/parsers/docker.py
- spython/version.py
This issue will close #163, specifically warning the user that multistage builds are not supported, and ensuring that warnings are one per line. This is now the output given the changes - the warnings are moved to one line each, and the --from lines with copy are not supported.
```bash
$ spython recipe Dockerfile > testrecipe.def
WARNING ARG is not supported for Singularity! Add as ENV to the container or export SINGULARITYENV_PROJ_INSTALL_PREFIX=/usr/local on the host.
WARNING ARG is not supported for Singularity! Add as ENV to the container or export SINGULARITYENV_BASE_IMAGE=ubuntu:20.04 on the host.
WARNING ARG is not supported for Singularity! Add as ENV to the container or export SINGULARITYENV_KEA_VERSION=1.4.13 on the host.
WARNING ARG is not supported for Singularity! Add as ENV …
```
> Ensuring that we dont support multistage builds

- .github/workflows/main.yml
- CHANGELOG.md
- spython/image/__init__.py
- spython/instance/cmd/logs.py
- spython/main/base/__init__.py
- spython/main/parse/parsers/docker.py
- spython/main/parse/writers/docker.py
- spython/oci/__init__.py
- spython/version.py
Signed-off-by: vsoch <vsochat@stanford.edu>
> adding pyflakes to check for unused imports and issues

- CHANGELOG.md
- spython/main/instances.py
- spython/version.py
It looks like older versions of singularity don't have the logerr/logout paths for an instance list, so we need to make them all optional.
> need to support old daemon_name, etc

- CHANGELOG.md
- spython/instance/__init__.py
- spython/instance/cmd/start.py
- spython/instance/cmd/stop.py
- spython/version.py
> Adding more verbosity for instance start/stop commands

- CHANGELOG.md
- spython/main/pull.py
- spython/version.py
> support pulling from https

- CHANGELOG.md
- spython/main/pull.py
- spython/utils/terminal.py
- spython/version.py
The previous singularity pull used to write to stdout so it would be possible to see the messages. The current writes completely to stderr, so the default for the pull function stream should be to return that.
Example:
```python
from spython.main import Client
image, stream = Client.pull('docker://busybox', stream=True)
singularity pull --name busybox.sif docker://busybox
for line in stream:
print(line.strip())
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:b71f96345d44b237decc0c2d6c2f9ad0d17fde83dad7579608f1f0764d9686f2
Copying config sha256:37c1493cd5ea164a5fc4ea85b649851682ca5a954f3d301530042af65290a5c7
Writing manifest to image destination
Storing signatures
2021/06/17 21:45:23  info unpack layer: …
```
> Fixing changed behavior with singularity pull

- CHANGELOG.md
- spython/instance/__init__.py
- spython/instance/cmd/start.py
- spython/version.py
This will address #178. It's hard to open a PR on airflow so hopefully we can fix the bug over here!
Signed-off-by: vsoch <vsoch@users.noreply.github.com
> Ensuring options and args are used if set from instance init

- CHANGELOG.md
- spython/main/parse/parsers/singularity.py
- spython/version.py
currently, it is assumed the comments and sections come after the header. However, we
need to allow comments before because it is not unheard of (although it seems rare). This will fix #180 
> Fixing parsing bug with singularity cli

- CHANGELOG.md
- spython/main/parse/parsers/base.py
- spython/utils/terminal.py
- spython/version.py
they show up for:
* re (python 3.9.7)
* semver 2.13.0
> silence deprecation warnings

- CHANGELOG.md
- spython/main/base/command.py
- spython/main/instances.py
- spython/main/run.py
- spython/utils/terminal.py
- spython/version.py
> preparing to add support for background run

- spython/main/parse/parsers/docker.py
Dockerfile WORKDIR creates a directory if it does not exist.   spython recipe conversion previously only generates "cd {dir}"
This adds "mkdir -p {dir}" before the "cd" to match the WORKDIR semantics in Dockerfiles.
> Match WORKDIR function in Dockerfile when converting to singularity recipe

- CHANGELOG.md
- docs/pages/commands.md
- spython/utils/terminal.py
- spython/version.py
> remove -E from sudo default

- CHANGELOG.md
- spython/main/parse/parsers/docker.py
- spython/version.py
> add support to parse stopsignal

- .github/dev-requirements.txt
- CHANGELOG.md
- setup.py
- spython/client/__init__.py
- spython/client/recipe.py
- spython/instance/__init__.py
- spython/instance/cmd/start.py
- spython/main/base/command.py
- spython/main/base/generate.py
- spython/main/build.py
- spython/main/execute.py
- spython/main/export.py
- spython/main/instances.py
- spython/main/parse/parsers/base.py
- spython/main/parse/parsers/docker.py
- spython/main/parse/parsers/singularity.py
- spython/main/parse/recipe.py
- spython/main/parse/writers/docker.py
- spython/main/parse/writers/singularity.py
- spython/main/pull.py
- spython/oci/__init__.py
- spython/oci/cmd/actions.py
- spython/oci/cmd/states.py
- spython/tests/test_client.py
- spython/tests/test_conversion.py
- spython/utils/terminal.py
- spython/version.py
This is an untested PR, but one I hope is fairly straightforward. I have a container whose program within it only outputs on the stderr. When streaming I am via the `Client.execute` method I am unable to capture these messages and log them. 
This PR aims to:
- expose the output_type option in execute (I have called it stream_type for clarity in the call into execute)
- ability to stream both the stdout and stderr. 
?
Would someone be able to give this a look over and test?
> Expose the output_type option when streaming, and allow both stdout/stderr to be captured

- CHANGELOG.md
- spython/utils/terminal.py
- spython/version.py
As discussed, sometimes an error is raised when there is no `stderr` attached to the `process` object. This will test to ensure it does exist before trying to read from it.
> test for stderr before printing

- CHANGELOG.md
- spython/instance/__init__.py
- spython/version.py
singularity-cli change provided instance name when it contains a dash to name with underscore.
dash is legit in instance name (see: `authorizedChars`  regexp in https://github.com/sylabs/singularity/blob/main/internal/pkg/instance/instance_linux.go#L69)
so do not change the name and delegate instance name validation to singularity.
regards
Eric
> do not change instance name
